document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'/>");
document.writeln("		<meta name=\'viewport\' id=\'vp\' content=\'initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\'>");
document.writeln("		<title></title>");
document.writeln("		<link rel=\'stylesheet\' href=\'./css/mobilebase.css\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'./css/battery.css\'>");
document.writeln("		<!-- 引入jquery -->");
document.writeln("		<script src=\'https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js\'></script>");
document.writeln("	</head>");
document.writeln("	<body onload=\'showTime()\'>");
document.writeln("		<div id=\'hangB\'>");
document.writeln("			<img class=\'hang l\' src=\'./img/signalB.png\'>");
document.writeln("			<section class=\'hang\' id=\'time\'>");
document.writeln("			</section>");
document.writeln("			<img class=\'hang r\' src=\'./img/batteryB.png\'>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("	<script>");
document.writeln("		// 如果数字为7，把它变成07");
document.writeln("		function checkTime(i) {");
document.writeln("			if (i < 10) {");
document.writeln("				i = \'0\' + i;");
document.writeln("			}");
document.writeln("			return i;");
document.writeln("		}");
document.writeln("		function showTime() {");
document.writeln("			let myDate = new Date(),");
document.writeln("			 h = myDate.getHours(),");
document.writeln("			 m = myDate.getMinutes(),");
document.writeln("			 s = myDate.getSeconds(),");
document.writeln("			 ap = \'\';");
document.writeln("			 h = checkTime(h);");
document.writeln("			 m = checkTime(m);");
document.writeln("			 s = checkTime(s);");
document.writeln("			 ap = h > 11 ? \' PM\' : \' AM\';");
document.writeln("			 $(\'#time\').text(h + \':\' + m + \':\' + s + ap);");
document.writeln("			 setTimeout(showTime, 1000);	");
document.writeln("		}");
document.writeln("	</script>");
document.writeln("</html>");